### ISSUE TITLE
Other Records Types

### ISSUE THREAD

**Issue by necrogami** [Badcow/DNS#10]
SRV
DNSSEC

It's a great library and i'd love to use it if i had these other entry types.

**Comment by cybernet** [comment]
+1

**Comment by samuelwilliams** [comment]
Agree. Currently on holidays and away from computer. Did you wanna try a pull request? The class should be pretty straight forward. Otherwise I'll have a look when I'm back from holidays.

**Comment by samuelwilliams** [comment]
SRV type has been created. DNSSEC has been moved to issue #16 and a new branch created for that purpose.
