### ISSUE TITLE
Not a valid resource record name

### ISSUE THREAD

**Issue by necrogami** [Badcow/DNS#11]
PHP Fatal error:  Uncaught Badcow\DNS\DNSException: "google._domainkey" is not a valid resource record name. in /Users/necrogami/code/dt/vendor/badcow/dns/lib/ResourceRecord.php:96
Stack trace:
#0 /Users/necrogami/code/dt/vendor/badcow/dns/lib/ResourceRecord.php(59): Badcow\DNS\ResourceRecord->setName('google._domaink...')
#1 /Users/necrogami/code/dt/random.php(88): Badcow\DNS\ResourceRecord->__construct('google._domaink...')
#2 {main}
  thrown in /Users/necrogami/code/dt/vendor/badcow/dns/lib/ResourceRecord.php on line 96

Code Snippet
```
$txt3 = new ResourceRecord('google._domainkey');
$txt3->setRdata(Factory::txt('v=DKIM1; k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDazaxHRVRVE1vnA3j02HvwgWcIhs2RWZ4U0aXknRapSSeTolKvFgnS+EYRRs8THeUdUDSiGYl5avuru10oIxNbcActybF+YIPClGdGGaGXVFboAs/EZFdUfHrCop/9DzxqS1jYHp33d+P9xoVi8ouQFs1AzoyyBVR0gwbIq8EIHQIDAQAB'));
$zone->addResourceRecord($txt3);
```

**Comment by necrogami** [comment]
It doesn't seem to like the underscore which is common in srv and txt records

**Comment by samuelwilliams** [comment]
Agreed, this should be changed. Strictly speaking, a non-alphanumeric character at the start of the string is not a valid resource name, that is why it fails. I'm starting to lean to the idea of getting rid of the validation on the resource records altogether and putting the onus on the developers to validate the resource names in their applications. Thoughts?

**Comment by necrogami** [comment]
Yeah, i'm more of the mindset a tool like this should push the validation to higher up the chain. This is more about generating the zone file vs validating a zone file that should be done for a parser or the upstream libraries.

**Comment by samuelwilliams** [comment]
Validation has been removed from the ResourceRecord object. Note that the validator will still validate some Rdata types (e.g. A and MX). This should resolve @necrogami issue.
