### ISSUE TITLE
Wildcards not supported

### ISSUE THREAD

**Issue by mlhess** [Badcow/DNS#2]
$wc->setName('*');

The name is not a Fully Qualified Domain Name in Badcow\DNS\ResourceRecord->setName() (line 71 of ---/badcow/dns/lib/ResourceRecord.php).

Is this not supported by the RFC?

**Comment by samuelwilliams** [comment]
Thanks for the issue @mlhess. This has been fixed and added to the latest release (v0.13) let me know how your use cases go.
