### ISSUE TITLE
Get a new version

### ISSUE THREAD

**Issue by Livda** [Badcow/DNS#22]
Have you plan to make many more updates to this lib before creating a v1.1 or a v1.0.1 ? I'll be glad if the update you've just merged could be used not only by pulling master

**Comment by samuelwilliams** [comment]
@Livda Thanks for the reminder, the library is at v1.1.

Out of interest, what are you using the library for?

**Comment by Livda** [comment]
Thanks a lot !

It'll be used to generate pretty DNS files. The idea is to manage the DNS of my company in a user-friendly way with a front, but still keep clean files if a human needs to edit them. Do you plan to finish your DNS reader ? It'll be awesome because currently I'm matching the objects returned by LTD-Beget/dns-zone-configurator with your objects, but it's a bit painful to remap everything because you don't do exactly like they do.

**Comment by samuelwilliams** [comment]
I had a good look at `LTD-Beget/dns-zone-configurator` and it seems very complex. I have used some of his ideas and rewritten my own parser [Badcow/DNS-Parser](https://github.com/Badcow/DNS-Parser).
It will output ResourceRecord object. It is working well but is a bit light on tests. Give it a whirl and tell me what you think.

**Comment by Livda** [comment]
Again, a new release is planned ? Pulling master with a specific commit tag works, but pulling a fixed version is better :wink:

**Comment by samuelwilliams** [comment]
Thanks for the reminder. v2.0.2 is now live.
