### ISSUE TITLE
Update parser to read the comments

### ISSUE THREAD

**Issue by Livda** [Badcow/DNS#30]
A `ResourceRecord` have an attribute `comment` and the builders write them, but we lose the comments on the reading of the file previously generated by the builder. Is it's possible to improve the parser and have the comments in the `ResourceRecord` object ?

**Comment by samuelwilliams** [comment]
This is a hard design consideration as there are two factors for which I don't have an answer:
## 1) Multi-line comments
Take the SOA record:
```
abc.com      IN SOA  (
                     example.com.      ; MNAME
                     post.example.com. ; RNAME
                     2014110501        ; SERIAL
                     3600              ; REFRESH
                     14400             ; RETRY
                     604800            ; EXPIRE
                     3600              ; MINIMUM
                     ); The comment on the ResourceRecord
```
Do I take the comment on each line and mash them together or only consider the last line? My comment could end up looking like `MNAME RNAME SERIAL REFRESH RETRY EXPIRE MINIMUM The comment on the ResourceRecord`, in which case the comment grows with every parse and output.

## 2) Comments not tied to Resource Records
Take the example:
```
; THE FOLLOWING ARE FOR THE MAIL SERVER
mx IN A 101.200.35.54
mx IN AAAA 2001:aca::54
@ IN MX 10 mx
```

I could have a blank resource record for the comment at the top, but that could get placed somewhere else as the records can get re-ordered in the `AlignedBuilder`

I saw two options, pick and choose which comments I keep or ignore them all. I do know that there probably is a better way. I could make this configurable to suit the end-developer.

Thoughts?

**Comment by Livda** [comment]
I think the only "valid" comment for the SOA record is the one in the last line. All the other comments should not be updated because they are pretty expressive by themselves. It could be a nice feature to edit this inner comments to explain with words the times like `; EXPIRE  (2 days)`, but i don't think it's a requirement.

And for the comments not tied to a Resource Records, I think they should be ignored. Like you said, all the records a reordered with the `AlignedBuilder` so all the context linked to this orphan comment are lost.

In my opinion, the comments are only available at the end of a record like the `AlignedBuilder` and the `ResourceRecord` model allow us to generate.

**Comment by samuelwilliams** [comment]
G'Day @Livda 

Thanks for this issue, I know it's been a while coming but I think I've got something for you.

Check out [this new branch](https://github.com/Badcow/DNS/tree/comments) which will allow you to retain DNS comments. I have been pragmatic and decided to keep _all_ comments, but I think I will make this configurable so that you can ignore comments within multi-line records, and ignore comments without resource entries.

[Check out this gist](https://gist.github.com/samuelwilliams/8d49108c1728d67879eebf1e03cfb17b) to give it a whirl.

Please let me know what you think!

**Comment by Livda** [comment]
Good day @samuelwilliams !

You've done an amazing work :smile: 

After a quick play with your gist, I've encounter 2 issues :
- A blank line is needed at the end in order to handle the last comment
- The comments of the SOA are a bit confusing

I've use the following example 
```
@            IN SOA  (
                     example.com.       ; MNAME
                     post.example.com.  ; RNAME
                     2014110501         ; SERIAL
                     3600               ; REFRESH 1 hour
                     14400              ; RETRY 4 hours
                     604800             ; EXPIRE  1 week
                     3600               ; MINIMUM 1 hour
                     ); This is my Start of Authority Record; AKA SOA.
```

and it generate this 
```
@            IN SOA  (
                     example.com.      ; MNAME
                     post.example.com. ; RNAME
                     2014110501        ; SERIAL
                     3600              ; REFRESH
                     14400             ; RETRY
                     604800            ; EXPIRE
                     3600              ; MINIMUM
                     ); MNAME RNAME SERIAL REFRESH 1 hour RETRY 4 hours EXPIRE 1 week MINIMUM 1 hour This is my Start of Authority Record; AKA SOA.
```
And if I parse again this zone with the long comment at the end of the record, the final comment have grown again. I don't think it's the behaviour wanted.

**Comment by samuelwilliams** [comment]
Thanks @Livda 

Blank line at the end is noted, I'll look into it.

I could foresee the issue of the growing comment line - I think I will make comment handling configurable. I am not entirely comfortable with parsing comments untied to a resource record either, so I might give developers the flexibility to choose how comments are handled if at all.

Thanks for the feedback.

-Sam

**Comment by samuelwilliams** [comment]
Hi again @Livda 

The comment parsing is now fully configurable!

Please check out the current commit on the `comments` branch. It goes hand-in-hand with the new [doc entry](https://github.com/Badcow/DNS/blob/comments/docs/Parser/Parsing-Comments.md).

Please let me know what you think of both the feature and the documentation.

Many thanks,

Sam

**Comment by Livda** [comment]
Hi again @samuelwilliams!
The new way to handle comments with the configuration seems to works perfectly. 
But I've a doubt about the way to configure the parser. Why are you using a bit mask instead of a configuration array like the Symfony's [HttpClientInterface](https://github.com/symfony/symfony/blob/0d4914149d3f89661ecf3103572f061fe1020834/src/Symfony/Contracts/HttpClient/HttpClientInterface.php#L28) does ? I've never encounter this way of configuration other than the Linux file system permission (the mithy `chmod 777`), so it's a bit surprising to use it here !

But you've done a awesome job :clap:, thanks !

**Comment by samuelwilliams** [comment]
Thanks @Livda 
I got the whole bitmask thing from [PHP Error Reporting](https://www.php.net/manual/en/function.error-reporting.php). I've merged it into master and will make a new release.

Thanks for the issue!
