### ISSUE TITLE
The content of a TXT record can be without quotes

### ISSUE THREAD

**Issue by frankvanhest** [Badcow/DNS#35]
In bind, as far as I know, it is allowed not to use quotes in TXT record. In Badcow\DNS\Parser\RdataHandlers::handleTxt the parsing stops when the content of the record does not start with a double quote.
Is it possible to fix this?
I use you package to parse bind files which live in DirectAdmin and there are a lot of zones with no quotes in the TXT record content.

Hopefully you can help me out.

**Comment by samuelwilliams** [comment]
I did a bit of a search around and as far as I can tell, TXT records without quotations are invalid, so I am not convinced to change the implementation. But, [you can add a custom Rdata handler](https://github.com/Badcow/DNS/blob/master/docs/Parser/Custom-Rdata-Handlers.md) to change the way that TXT records are processed. I haven't tried this because my dog is hassling me to go play, but it might look like this:

```php
function franksTxtHandler(StringIterator $string, StringIterator $txt) {
        while ($string->isNot(Tokens::LINE_FEED) && $string->valid()) {
            if ($string->is(Tokens::BACKSLASH)) {
                $string->next();
            }

            $txt->append($string->current());
            $string->next();
        }
    }
```

I hope this helps :)

**Comment by samuelwilliams** [comment]
I have made and tested a handler for you, now that my dog is distracted...
[https://gist.github.com/samuelwilliams/460beee45fe9d6148d586e7966076d74](https://gist.github.com/samuelwilliams/460beee45fe9d6148d586e7966076d74)

**Comment by frankvanhest** [comment]
You should always prioritise playing with your dog. I know the "problem".
Thanks your code! I didn't realise that I could create my own handlers. Sorry for that.

**Comment by lorenzbausch** [comment]
If I understand the [corresponding RFC](https://www.ietf.org/rfc/rfc1035.txt) correctly (see `3.3.14. TXT RDATA format`) , TXT records need to be in the following format: `TXT-DATA        One or more <character-string>s.` where `<character-string>` is defined like this:
```
<character-string> is expressed in one or two ways: as a contiguous set
of characters without interior spaces, or as a string beginning with a "
and ending with a ".  Inside a " delimited string any character can
occur, except for a " itself, which must be quoted using \ (back slash).
```

To the best of my understanding this means that both of the following records are valid:
```
zone.tld.	900	IN	TXT	"foo bar"
zone.tld.	900	IN	TXT	foobar
```
