### ISSUE TITLE
Support for reverse zones

### ISSUE THREAD

**Issue by Furgas** [Badcow/DNS#4]
Currently there is no PTR RR implementation and `Validator::validateFqdn` method doesn't properly validate reverse zone names.

**Comment by samuelwilliams** [comment]
An IN-APPR.ADDR is not a valid host name - so the validator is going to fail.

There are two possible ways of addressing the issue:

1. We let `Validator::validateFqdn()` pass a host locator as true, or

2. We extend `ResourceRecord` and make a special `PtrRR` that supports the host locator.

Thoughts?

**Comment by Furgas** [comment]
I had something along case 2. in mind:
- introduce separate validation methods for reverse zone names and PTR names (watch out for IPv4 vs IPv6)
- make `ReverseZone extends Zone` with setName calling proper validation rule
- make `ReverseResourceRecord extends ResourceRecord` with setName calling proper validation rule
- make `PtrRdata implements RdataInterface`

**Comment by samuelwilliams** [comment]
Could you make a pull request? That sounds like a good bit of work.

**Comment by Furgas** [comment]
I'll try to find some time. Currently I'm using custom ReverseZone and ReverseResourceRecord without any validation in setName ;)

**Comment by samuelwilliams** [comment]
Hi again @Furgas 
Thanks again for your use case scenario. I have updated the repo to support reverse records. This works for both IPv4 and IPv6.

I decided to go with something akin to Option 1 as I felt that adding special resource records would not be ideal.

Give it a whirl and tell me what you think.
