### ISSUE TITLE
RRSIG Records not ordered in AlignedBuilder

### ISSUE THREAD

**Issue by samuelwilliams** [Badcow/DNS#61]
AlignedBuilder::build( $zone ) groups A, CNAME etc nicely together, but NSEC3 & RRSIG are in order found in source zone file with comments inserted whenever type changes (and it does change repeatedly). Result is valid, but could look better.

Source: [poose.eu.zone.txt](https://github.com/Badcow/DNS/files/4009670/poose.eu.zone.txt)

Output:
![Screenshot 2019-12-30 at 13 34 18](https://user-images.githubusercontent.com/712310/71580389-22658500-2b09-11ea-8621-abc88bf98123.png)

_Originally posted by @petskratt in https://github.com/Badcow/DNS/issues/60#issuecomment-569654351_

**Comment by samuelwilliams** [comment]
The ordering has been fixed in new branch. Additionally, I have added an output formatter for RRSIG.

This will be merged into master and added to the next bugfix release.

**Comment by samuelwilliams** [comment]
Merged.

**Comment by petskratt** [comment]
Thanks, great :)

We got exactly yesterday a customer request to have more readable zones, with DNSSEC sorted to end (and start of zone easily inspectable by humans).
