### ISSUE TITLE
Invalid TTL and name when record name is numeric 

### ISSUE THREAD

**Issue by a3dho3yn** [Badcow/DNS#72]
In [RFC1035](https://tools.ietf.org/html/rfc1035) the structure of an entry is defined as:

> ```
>     <domain-name><rr> [<comment>]
>     <blank><rr> [<comment>]
> ```
> If an entry for an RR begins with a blank, then the RR is assumed to be owned by the last stated owner.  If an RR entry begins with a < domain-name >, then the owner name is reset.
> 
> ```
> <rr> contents take one of the following forms:
>     [<TTL>] [<class>] <type> <RDATA>
>     [<class>] [<TTL>] <type> <RDATA>
> ```
> The RR begins with optional TTL and class fields, followed by a type and RDATA field appropriate to the type and class.  Class and type use the standard mnemonics, TTL is a decimal integer.  Omitted class and TTL values are default to the last explicitly stated values.

But when we pass an entry like `123 A 1.2.3.4` to the parser, it will consider that:
- name is blank (so it's owned by the last stated owner)
- TTL is 123

Where -based on RFC1035- it's expected to:
- see `123` as name
- use last stated or default TTL

**Comment by a3dho3yn** [comment]
I've inspected to code and found that the problem is with the algorithm of [`Parser:: processEntry`](https://github.com/Badcow/DNS/blob/master/lib/Parser/Parser.php#L147). It iterates over the elements and first of all checks whether it `isTTL` or not. `isTTL` assumes a time format string followed by `<class> <type>` or `<type>` as TTL; which is a invalid definition for `123 A 1.2.3.4`.

**Comment by a3dho3yn** [comment]
Another issue is with [trimming whitespaces](https://github.com/Badcow/DNS/blob/1b54b9f7cc4f0e54194b3f97d901c8156c52c3e0/lib/Parser/Normaliser.php#L200) from the beginning of the lines. When white spaces are removed, these two records will look same:
- ` 123 A 1.2.3.4 ; <blank><TTL> <type> <RDATA>`
- `123 A 1.2.3.4 ; <domain-name> <type> <RDATA>`
And it's not possible to parse the entry correctly.

**Comment by a3dho3yn** [comment]
@samuelwilliams

**Comment by samuelwilliams** [comment]
Hi - Sorry for leaving you hanging so long.
Thank you for your PR - I have merged this into master which will be released as part of an upcoming v4.
