### ISSUE TITLE
Explicit support for PHP 8.0

### ISSUE THREAD

**Issue by AdnanHussainTurki** [Badcow/DNS#96]
Badcow/DNS Version 4.1 provides explicit support for PHP 8.0 but the "rlanvin/php-ip": "^2.0" is not supporting PHP 8.0 right now

**Comment by samuelwilliams** [comment]
Hi @AdnanHussainTurki 

I have made a small change in the composer file to use the rlanvin/phpip PHP 8.0 development branch. When running tests, one of the tests errors with a deprecation error, but otherwise the tests run fine. This has been push as version 4.1.1

Thanks for the issue!

**Comment by AdnanHussainTurki** [comment]
Great. Thanks Samuel.
